name = "green-engine-v6-3-15-cf"
main = "worker/index.js"
compatibility_date = "2026-08-12"

preview_urls = false

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[secrets]
required = ["API_FOOTBALL_KEY"]

[vars]
ALLOWED_ORIGINS = "https://helitonsf.github.io,https://green-engine-v6-3-15-cf.gerenteheliton.workers.dev,https://green-engine-v6-3-16-cf.gerenteheliton.workers.dev"
